### ISSUE TITLE
Problem using the plugin

### ISSUE THREAD

**Issue by Greenbald** [w8r/Leaflet.draw.drag#10]
Hey there, sorry to bother you. 

I am trying to use your plugin, but I am getting this error in the _enableDragging function, chrome tells me that the error is : **Uncaught TypeError: L.Handler.PathDrag is not a function** . (Line 77)

I am not a javascript expert, so I have no idea how to solve this problem. If you could help me, would be great. Thanks.

Hugs.

**Comment by Greenbald** [comment]
Oh, my bad. I figure out what the problem was, I needed to include Leaflet.Path.Drag.

But now I have another problem, when moving some polygon in the edit mode, I receive this error(Every time I drop the polygon) : 

**Uncaught TypeError: Cannot read property 'call' of undefined**

The error happens here : 

**L.Edit.SimpleShape.prototype._updateMoveMarker.call(this); (Line 127)**

**Comment by w8r** [comment]
@Greenbald, hi, can you provide me with a jsfiddle to see the error, please? I cannot reproduce it on the latest version

**Comment by w8r** [comment]
Or the version of leaflet.draw you use

**Comment by Greenbald** [comment]
Hi @w8r , I just commented this line and worked like a charm. I do not know what kind of problems I will have by commenting that, but until now I did not find any error.

Thank you for your attention and help!
