### ISSUE TITLE
Work this plugin with Leaflet 1.0?

### ISSUE THREAD

**Issue by ddmactive** [w8r/Leaflet.draw.drag#14]
Thanks in advance

**Comment by w8r** [comment]
I am planning to release a new version with support of 1.0

**Comment by ddmactive** [comment]
Thanks again for your excellent work

**Comment by sinires** [comment]
Hello.
This project is still alive?

**Comment by w8r** [comment]
Hi, the version `0.4.3` is compatible with `leaflet@1.x` and `leaflet-draw@0.4.x`

**Comment by sinires** [comment]
thx u
