### ISSUE TITLE
The problem of dragging polyline

### ISSUE THREAD

**Issue by sinires** [w8r/Leaflet.draw.drag#16]
Hello, when i drawing polyline the control points have last positions.  
I am submitting a screenshot of the demo
![2016-11-24 14 09 38](https://cloud.githubusercontent.com/assets/20899539/20596873/af016c42-b251-11e6-911c-2e793d2f88b7.png)

**Comment by iofirag** [comment]
+1

**Comment by BenGedi** [comment]
+1

**Comment by salnikovp0** [comment]
+1

**Comment by iofirag** [comment]
thanks!
