### ISSUE TITLE
css not included in this package

### ISSUE THREAD

**Issue by iofirag** [w8r/Leaflet.draw.drag#18]
All the css of the panel draw buttons are missing
temp solution is to include Leaflet.draw css

**Comment by BenGedi** [comment]
+1

**Comment by tomscholz** [comment]
Please stop writing +1. It is just annoying especially, because you can use the github reactions

**Comment by w8r** [comment]
But what do you mean? Leaflet.draw.drag doesn't require CSS

**Comment by iofirag** [comment]
to use your package i write 
`import 'leaflet-draw-drag'; ` as you write in the example use.
but all the style of the draw-bar are missing.
since you dont have the style file (css) of Leaflet-draw

so i suggest for people that using your package to import the css of Leaflet.draw also
`import 'leaflet-draw/dist/leaflet.draw.css';`
as a fix solution.

**Comment by w8r** [comment]
`leaflet-draw-drag` is an additional behaviour **on top** of `leaflet-draw`. It does not add a single CSS rule, and cannot be used without leaflet-draw. So yes, you have to add `leaflet-draw` styles separately if you want to make use of its drawing panel.

**Comment by iofirag** [comment]
ok, now it's more clearly then the Read me :)
