### ISSUE TITLE
question: clicks being suppressed after drag

### ISSUE THREAD

**Issue by dremonkey** [w8r/Leaflet.draw.drag#4]
Which source file is this actually coming from? https://github.com/w8r/Leaflet.draw.drag/blob/d1baa5dbdfd8b71548cfeb7c7b8d2df604ff2f96/dist/Leaflet.draw.drag-src.js#L91-L107 I'm pretty sure it is causing problems for me (i.e suppressing clicks after the shape has been dragged) but I want to do some more testing to be sure but can't seem to find this bit of code anywhere.

**Comment by w8r** [comment]
@dremonkey  I took that from `Marker.Drag` behaviour, I think. But are you sure it's breaking something? In my testcase problem was the opposite: attached popup was triggered every time I dragged the feature

**Comment by dremonkey** [comment]
Haven't had a chance to do much testing on it so not positive what is happening yet. It may be related to my specific implementation because I am doing some unconventional stuff with how I attach/detach listeners. Just noticed that after I installed the latest code, the click events stopped firing after a drag. Anyway I will try to do some testing this week and let you know if I find something.

**Comment by dos65** [comment]
@w8r I have this problem too. I had to override this behavior for L.Polygon.

**Comment by dos65** [comment]
Here is [fix](https://github.com/dos65/Leaflet.Path.Drag/commit/0bce9fc796dac72073f432a492975961ac409967) for Leaflet.Path.Drag.

**Comment by w8r** [comment]
@dos65, @dremonkey:  Not sure if I can reproduce that. Let's take a look at [the demo](http://w8r.github.io/Leaflet.draw.drag/example/)
Polygons are exposed as `window.drawnItems`. I add a `click` listener to one of them as follows
```js
drawnItems.on('click', function(evt){ console.log('click', e); });
```

Each of the visible layers is responding to clicks as expected, also after switching editing mode on and off several times. Chrome 42 Win, Mac OS X, IE11. Can you provide a jsfiddle or some other showcase or scenario where the click handlers stop working?

**Comment by dos65** [comment]
@dremonkey  It can be reproduced only after dragging feature.

**Comment by w8r** [comment]
@dos65, Yes, that's what I did, still can't reproduce that. Do you get that on the demo page?

**Comment by dos65** [comment]
Yes. Some comments above i gave [link](https://github.com/dos65/Leaflet.Path.Drag/commit/0bce9fc796dac72073f432a492975961ac409967) to my fork, where i found that `dragging.moved`method still return true after dragging, so `L.Path._onMouseClick` can't go to `fireClickEvent`.

**Comment by w8r** [comment]
I don't understand how that's happening. The `_dragMoved` flag is set to `false` on every `mousedown` event. So logically it cannot persist to the click after the dragging had occurred, click is only suppressed once. Maybe we are talking about a touch device?

**Comment by dos65** [comment]
No :) Maybe it depends of platform. I get that on Chromium 41, FF 37 Linux. I'll try to do obvious test-case example.

**Comment by w8r** [comment]
@dos65 спасибо!

**Comment by joongtang** [comment]
I have same problem. so I added one line code in _onDragEnd function 
```javascript
+ 246 this._path._dragMoved = false;
```
then I can delete dragged feature!

**Comment by w8r** [comment]
@joongtang that's the solution, now I understand it! Thanks. I'm gonna update the code
