### ISSUE TITLE
Multiple vector drag

### ISSUE THREAD

**Issue by SirenHound** [w8r/Leaflet.draw.drag#5]
I have been trying to implement this feature into a project where I would like to drag multiple layers around a map by dragging one 'parent' layer.

For instance, say I have a rectangle and a circle, dragging the rectangle should also drag the circle by the same amount, and ideally attempting to drag the circle should do nothing (but I don't want to get ahead of myself)

Is there an easy way to do this?

**Comment by w8r** [comment]
I doubt about an easy way, but you can take a look at that

https://github.com/w8r/Leaflet.Path.Drag/blob/master/src/MultiPoly.Drag.js

That's the code behind `MultiPolygon` dragging, it can be adapted to work with one handler (rectangle in your case) and a `LayerGroup` of vector features
